### ISSUE TITLE
Лабораторная работа №2

### ISSUE THREAD

**Issue by trtpo** [evgenyzhurko/Cloudlet#1]
Evgeny,
I still don't see relevance between mockups and actual requirements.
You also forgot to "explain why non-functional requirements are important and how they will be measured" as required in:  https://drive.google.com/open?id=0B9re064DeEzKWkUzSmNVdkVNY3c

**Comment by evgenyzhurko** [comment]
Thanks, 
I added missing items in requirements and corrected mockups.
